name: CI MLOps - Random Forest

on:
  push:
    branches:
      - main

jobs:
  test_and_validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: pip install pandas scikit-learn numpy flake8

      - name: Linting (Verificar sintaxe)
        run: flake8 src/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
        
      - name: Testes do Modelo de Regressão (Frete)
        run: python -m unittest tests/test_regressao.py
          
  deploy_aws:
    needs: test_and_validate # SÓ RODA SE OS TESTES FICAREM VERDES!
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Só faz deploy se estiver na branch principal

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências da AWS
        run: pip install boto3 "sagemaker<3" scikit-learn==1.4.2 joblib

      - name: Executar Deploy no SageMaker
        env:
          # O robô puxa as senhas do cofre que você acabou de criar!
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-west-2"
        run: |
          python src/deploy_sagemaker.py